name: rummy_pro
description: Production-ready multi-game Rummy app with wallet support.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  firebase_remote_config: ^5.0.1
  firebase_storage: ^12.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  collection: ^1.18.0
  csv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/strings/
  generate: true

